# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='NetMsgBus.PBParam.proto',
  package='NetMsgBus',
  serialized_pb='\n\x17NetMsgBus.PBParam.proto\x12\tNetMsgBus\"*\n\x12PBQueryServicesReq\x12\x14\n\x0cmatch_prefix\x18\x01 \x02(\t\"*\n\x12PBQueryServicesRsp\x12\x14\n\x0cservice_name\x18\x01 \x03(\t\"@\n\x12PBQueryMessagesReq\x12\x14\n\x0cservice_name\x18\x01 \x02(\t\x12\x14\n\x0cmatch_prefix\x18\x02 \x02(\t\"@\n\x12PBQueryMessagesRsp\x12\x14\n\x0cservice_name\x18\x01 \x02(\t\x12\x14\n\x0cmessage_name\x18\x02 \x03(\t\"L\n\x0cPBClientInfo\x12\x11\n\tclient_ip\x18\x01 \x02(\r\x12\x13\n\x0b\x63lient_port\x18\x02 \x02(\r\x12\x14\n\x0c\x63lient_state\x18\x03 \x02(\x11\"V\n\x10PBServiceClients\x12\x14\n\x0cservice_name\x18\x01 \x02(\t\x12,\n\x0b\x63lient_info\x18\x02 \x03(\x0b\x32\x17.NetMsgBus.PBClientInfo\"Z\n\x10PBSyncServerData\x12\x13\n\x0bserver_name\x18\x01 \x02(\t\x12\x31\n\x0cservice_info\x18\x02 \x03(\x0b\x32\x1b.NetMsgBus.PBServiceClients')




_PBQUERYSERVICESREQ = descriptor.Descriptor(
  name='PBQueryServicesReq',
  full_name='NetMsgBus.PBQueryServicesReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='match_prefix', full_name='NetMsgBus.PBQueryServicesReq.match_prefix', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=38,
  serialized_end=80,
)


_PBQUERYSERVICESRSP = descriptor.Descriptor(
  name='PBQueryServicesRsp',
  full_name='NetMsgBus.PBQueryServicesRsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='service_name', full_name='NetMsgBus.PBQueryServicesRsp.service_name', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=82,
  serialized_end=124,
)


_PBQUERYMESSAGESREQ = descriptor.Descriptor(
  name='PBQueryMessagesReq',
  full_name='NetMsgBus.PBQueryMessagesReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='service_name', full_name='NetMsgBus.PBQueryMessagesReq.service_name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='match_prefix', full_name='NetMsgBus.PBQueryMessagesReq.match_prefix', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=126,
  serialized_end=190,
)


_PBQUERYMESSAGESRSP = descriptor.Descriptor(
  name='PBQueryMessagesRsp',
  full_name='NetMsgBus.PBQueryMessagesRsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='service_name', full_name='NetMsgBus.PBQueryMessagesRsp.service_name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='message_name', full_name='NetMsgBus.PBQueryMessagesRsp.message_name', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=192,
  serialized_end=256,
)


_PBCLIENTINFO = descriptor.Descriptor(
  name='PBClientInfo',
  full_name='NetMsgBus.PBClientInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='client_ip', full_name='NetMsgBus.PBClientInfo.client_ip', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='client_port', full_name='NetMsgBus.PBClientInfo.client_port', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='client_state', full_name='NetMsgBus.PBClientInfo.client_state', index=2,
      number=3, type=17, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=258,
  serialized_end=334,
)


_PBSERVICECLIENTS = descriptor.Descriptor(
  name='PBServiceClients',
  full_name='NetMsgBus.PBServiceClients',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='service_name', full_name='NetMsgBus.PBServiceClients.service_name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='client_info', full_name='NetMsgBus.PBServiceClients.client_info', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=336,
  serialized_end=422,
)


_PBSYNCSERVERDATA = descriptor.Descriptor(
  name='PBSyncServerData',
  full_name='NetMsgBus.PBSyncServerData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='server_name', full_name='NetMsgBus.PBSyncServerData.server_name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='service_info', full_name='NetMsgBus.PBSyncServerData.service_info', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=424,
  serialized_end=514,
)

_PBSERVICECLIENTS.fields_by_name['client_info'].message_type = _PBCLIENTINFO
_PBSYNCSERVERDATA.fields_by_name['service_info'].message_type = _PBSERVICECLIENTS
DESCRIPTOR.message_types_by_name['PBQueryServicesReq'] = _PBQUERYSERVICESREQ
DESCRIPTOR.message_types_by_name['PBQueryServicesRsp'] = _PBQUERYSERVICESRSP
DESCRIPTOR.message_types_by_name['PBQueryMessagesReq'] = _PBQUERYMESSAGESREQ
DESCRIPTOR.message_types_by_name['PBQueryMessagesRsp'] = _PBQUERYMESSAGESRSP
DESCRIPTOR.message_types_by_name['PBClientInfo'] = _PBCLIENTINFO
DESCRIPTOR.message_types_by_name['PBServiceClients'] = _PBSERVICECLIENTS
DESCRIPTOR.message_types_by_name['PBSyncServerData'] = _PBSYNCSERVERDATA

class PBQueryServicesReq(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PBQUERYSERVICESREQ
  
  # @@protoc_insertion_point(class_scope:NetMsgBus.PBQueryServicesReq)

class PBQueryServicesRsp(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PBQUERYSERVICESRSP
  
  # @@protoc_insertion_point(class_scope:NetMsgBus.PBQueryServicesRsp)

class PBQueryMessagesReq(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PBQUERYMESSAGESREQ
  
  # @@protoc_insertion_point(class_scope:NetMsgBus.PBQueryMessagesReq)

class PBQueryMessagesRsp(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PBQUERYMESSAGESRSP
  
  # @@protoc_insertion_point(class_scope:NetMsgBus.PBQueryMessagesRsp)

class PBClientInfo(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PBCLIENTINFO
  
  # @@protoc_insertion_point(class_scope:NetMsgBus.PBClientInfo)

class PBServiceClients(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PBSERVICECLIENTS
  
  # @@protoc_insertion_point(class_scope:NetMsgBus.PBServiceClients)

class PBSyncServerData(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PBSYNCSERVERDATA
  
  # @@protoc_insertion_point(class_scope:NetMsgBus.PBSyncServerData)

# @@protoc_insertion_point(module_scope)
